config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#homepage'

  get 'aboutpage' , to: 'pages#aboutpage'

  resources :articles , only: [:show , :index , :new , :create , :edit , :update , :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   validates :title, presence: true ,length: {minimum:5 , maximum:50}
   validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article , only: [:show , :edit , :update , :destroy ]

    def show
        
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create

        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article created successfully"
            redirect_to @article
        else
            render 'new'
        end
        
    end

    def edit
        
    end

    def update
        
        if @article.update(article_params) 
            flash[:notice] = "Article updated successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
       
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article= Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title , :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def homepage

    end        

    def aboutpage

    end        

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<%= form_with(model: @article, locale: true ) do |f| %>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title%>
    </p>

    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit%>   
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>edit article</h1>



<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Show all articles</h1>


<table>
    <thead>
        <tr>
            <th>Title </th>
            <th>Description </th>
            <th colspan="3">Actions </th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td> <%= article.title %> </td>
            <td> <%= article.description %> </td>
            <td> <%= link_to 'SHOW' ,article_path(article)%></td>
            <td> <%= link_to 'EDIT' ,edit_article_path(article)%></td>
            <td> <%= link_to 'DELETE' ,article_path(article), method: :delete, data: {confirm:"Are you sure you want to delete"}%></td>
        </tr>
        <% end %>
    </tbody>
</table>


<p>
    <td> <%= link_to 'Create new article' ,new_article_path %></td>
</p>

app/views/articles/new.html.erb
<h1>Create new article</h1>



<%= render 'form'%>

app/views/articles/show.html.erb
<h1>SHOW Article</h1>
<h3>title : <%= @article.title %></h3>
<h3>description : <%= @article.description %></h3>

<%= link_to 'EDIT' ,edit_article_path(@article)%> |
<%= link_to 'DELETE' ,article_path(@article), method: :delete , data: {confirm:"Are you sure you want to delete"}%> |
<%= link_to 'Return to home' ,articles_path %>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <% render 'layouts/messages'%>
    
    <%= yield %>
  </body>
</html>

app/views/pages/aboutpage.html.erb
<h2>About Page</h2>

<%= link_to 'HOME PAGE' ,root_path %>

app/views/pages/homepage.html.erb
<h1>Home Page Welcome</h1>
<%= link_to 'Articles Page' ,articles_path %>
<%= link_to 'About Page' ,aboutpage_path %>